# Generated by Django 6.0 on 2025-12-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_add_yelp_and_featured_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='review_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['category'], name='finder_feat_categor_5a184c_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['location'], name='finder_feat_locatio_e5905f_idx'),
        ),
    ]
