# Generated by Django 6.0 on 2025-12-27 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_alter_featuredbusiness_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='last_paid_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='plan',
            field=models.CharField(choices=[('featured', 'Featured'), ('premium', 'Premium'), ('top', 'Top Slot')], default='featured', max_length=20),
        ),
        migrations.AlterField(
            model_name='featuredbusiness',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['plan'], name='finder_feat_plan_0a059a_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['priority'], name='finder_feat_priorit_56a3da_idx'),
        ),
    ]
