# Generated by Django 6.0 on 2025-12-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_featuredbusiness_last_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
