# Generated by Django 6.0 on 2025-12-29 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_promotionbid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='promotionbid',
            constraint=models.UniqueConstraint(fields=('term', 'location', 'business'), name='unique_bid_per_search_per_business'),
        ),
    ]
