# Generated by Django 6.0 on 2025-12-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_promotionbid_unique_bid_per_search_per_business'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promotionbid',
            name='finder_prom_term_77400b_idx',
        ),
        migrations.RemoveIndex(
            model_name='promotionbid',
            name='finder_prom_bid_cen_1e8980_idx',
        ),
        migrations.RemoveConstraint(
            model_name='promotionbid',
            name='unique_bid_per_search_per_business',
        ),
        migrations.RemoveIndex(
            model_name='featuredbusiness',
            name='finder_feat_categor_5a184c_idx',
        ),
        migrations.RemoveIndex(
            model_name='featuredbusiness',
            name='finder_feat_locatio_e5905f_idx',
        ),
        migrations.RemoveIndex(
            model_name='featuredbusiness',
            name='finder_feat_plan_0a059a_idx',
        ),
        migrations.RemoveIndex(
            model_name='featuredbusiness',
            name='finder_feat_priorit_56a3da_idx',
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featuredbusiness',
            name='yelp_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PromotionBid',
        ),
    ]
