# Generated by Django 6.0 on 2025-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_remove_promotionbid_finder_prom_term_77400b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='close_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='open_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
