# Generated by Django 6.0 on 2025-12-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_featuredbusiness_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='holiday_note',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='holiday_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='is_on_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
