# Generated by Django 6.0 on 2025-12-30 16:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_featuredbusiness_holiday_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredbusiness',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
        migrations.AlterField(
            model_name='featuredbusiness',
            name='close_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='featuredbusiness',
            name='open_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['name'], name='finder_feat_name_78f6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['category'], name='finder_feat_categor_5a184c_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['location'], name='finder_feat_locatio_e5905f_idx'),
        ),
        migrations.AddIndex(
            model_name='featuredbusiness',
            index=models.Index(fields=['is_active', 'priority'], name='finder_feat_is_acti_e842ab_idx'),
        ),
    ]
