# Generated by Django 6.0 on 2025-12-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0013_alter_featuredbusiness_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='directions_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='website_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
