# Generated by Django 6.0 on 2025-12-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0014_featuredbusiness_call_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='featuredbusiness',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
