# Generated by Django 6.0 on 2026-01-01 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0016_alter_featuredbusiness_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclaim',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='featuredbusiness',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='businessclaim',
            index=models.Index(fields=['status'], name='finder_busi_status_7ac896_idx'),
        ),
    ]
