# Generated by Django 6.0 on 2026-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0017_businessclaim_last_sent_at_businessclaim_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredbusiness',
            name='featured_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
